#!/usr/bin/env bash
#Install nginx on your web-01
#Nginx should be listening on port 80

# Methods to update the package list and install nginx
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

# To Create a custom index.html file with "Hello World!" message
echo "Hello World!" > /var/www/html/index.html

# Restart 
service nginx restart
