#!/usr/bin/env bash
#script that installs nginx on your web-01
#Once connected Nginx should be listen to port 80

apt-get -y update
apt-get -y install nginx

sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
service nginx restart
