#!/usr/bin/env bash
# Script displays numbers from 1 to 100 in list format.
# To displays "FizzBuzz" when the number is a multiple of 3 and 5.
# To displays "Fizz" when the number is a multiple of 3.
# To displays "Buzz" when the number is a multiple of 5.
# Otherwise, script to display the number.


for number in {1..100}
do
    if [ $((number % 3)) == 0 ] && [ $((number % 5)) == 0 ]
    then
        echo "FizzBuzz"
    elif [ $((number % 5)) == 0 ]
    then
        echo "Buzz"
    elif [ $((number % 3)) == 0 ]
    then
        echo "Fizz"
    else
        echo "$num"
    fi

done
